kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

include:
  - _redirects

# Exclude these files from our production _site
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - serve
  - wip
  - wget
