- id: 1
  name:
    - en: N3 NYLON FOUSTA 1
    - el: N3 ΝΥΛΟΝ ΦΟΥΣΤΑ 1
  description:
    - en:
    - el:
  images:
    - main: /assets/img/N3_NYLON_FOUSTA_1.png
    - thumb: /assets/img/N3_NYLON_FOUSTA_1-150x150.png
  category:
    - nylon
    - zipper
    - no3
- id: 2
  name:
    - en: N3 NYLON FOUSTA 2
    - el: N3 ΝΥΛΟΝ ΦΟΥΣΤΑ 2
  description:
    - en:
    - el:
  images:
    - main: /assets/img/N3_NYLON_FOUSTA_2.png
    - thumb: /assets/img/N3_NYLON_FOUSTA_2-150x150.png
  category:
    - nylon
    - zipper
    - no3
