- name:
  - el: "N3 NYLON FOUSTA 1"
  - en: "N3 NYLON SKIRT 1"
  - description:
    - el: ""
    - en: ""
  - images:
    - thumb: "/assets/images/products/N3_NYLON_FOUSTA_1-150x150.png"
    - main: "/assets/images/products/N3_NYLON_FOUSTA_1.png"
  - categories:
    - zippers
    - nylon
    - no3
- name:
  - el: "N3 NYLON FOUSTA 2"
  - en: "N3 NYLON SKIRT 2"
  - description:
    - el: ""
    - en: ""
  - images:
    - thumb: "/assets/images/products/N3_NYLON_FOUSTA_2-150x150.png"
    - main: "/assets/images/products/N3_NYLON_FOUSTA_2.png"
  - categories:
    - zippers
    - nylon
    - no3
- name:
  - el: "N3 NYLON SPECIAL 1"
  - en: "N3 NYLON SPECIAL 1"
  - description:
    - el: ""
    - en: ""
  - images:
    - thumb: "/assets/images/products/N3_NYLON_SPECIAL_1-150x150.png"
    - main: "/assets/images/products/N3_NYLON_SPECIAL_1.png"
  - categories:
    - zippers
    - nylon
    - no3
- name:
  - el: "N3 NYLON SPECIAL 2"
  - en: "N3 NYLON SPECIAL 2"
  - description:
    - el: ""
    - en: ""
  - images:
    - thumb: "/assets/images/products/N3_NYLON_SPECIAL_2-150x150.png"
    - main: "/assets/images/products/N3_NYLON_SPECIAL_2.png"
  - categories:
    - zippers
    - nylon
    - no3
- name:
  - el: "N3 NYLON SPECIAL 3"
  - en: "N3 NYLON SPECIAL 3"
  - description:
    - el: ""
    - en: ""
  - images:
    - thumb: "/assets/images/products/N3_NYLON_SPECIAL_3-150x150.png"
    - main: "/assets/images/products/N3_NYLON_SPECIAL_3.png"
  - categories:
    - zippers
    - nylon
    - no3
- name:
  - el: "N3 NYLON TRANS 1"
  - en: "N3 NYLON TRANS 1"
  - description:
    - el: ""
    - en: ""
  - images:
    - thumb: "/assets/images/products/N3_NYLON_TRANS_1-150x150.png"
    - main: "/assets/images/products/N3_NYLON_TRANS_1.png"
  - categories:
    - zippers
    - nylon
    - no3
- name:
  - el: "N3 ΚΟΚΑΛΙΝΟ ΔΙΑΧΩΡΙΖΟΜΕΝΟ 2WAY"
  - en: "N3 BONE SPLIT 2WAY"
  - description:
    - el: ""
    - en: ""
  - images:
    - thumb: "/assets/images/products/N3_KOKKALINO_SPECIAL_5.png"
    - main: "/assets/images/products/N3_KOKKALINO_SPECIAL_5.png"
  - categories:
    - zippers
    - nylon
    - no3
