backend:
  name: git-gateway
  branch: master

#publish_mode: 'editorial_workflow'
media_folder: 'assets/img'  # Media files will be stored in the repo under assets/files

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: single_file

  # Required - a list of locales to show in the editor UI
  locales: [el, en]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: el

collections:
  - name: "el"
    label: "Posts Greek"
    folder: "_posts/el"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "product"}
      - {label: "Language", name: "language", widget: "hidden", default: "el"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image_main", widget: "image"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Description", name: "description", widget: "markdown"}
  - name: "en"
    label: "Posts English"
    folder: "_posts/en"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "product"}
      - {label: "Language", name: "language", widget: "hidden", default: "en"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image_main", widget: "image"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Description", name: "description", widget: "markdown"}


  - name: posts
    label: "Test Posts"
    folder: "_posts2"
    create: true
    identifier_field: name
    i18n: true
    slug: "{{year}}-{{month}}-{{day}}-{{name}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "product"
      - label: "Name"
        name: "name"
        widget: "string"
        i18n: true
      - label: "Image"
        name: "image_main"
        widget: "image"
        i18n: duplicate
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - label: "Drivers"
            value: "drivers"
          - label: "Zippers"
            value: "zippers"
        i18n: duplicate
      - label: "Tags"
        name: "tags"
        widget: "list"
        i18n: duplicate
      - label: "Description"
        name: "description"
        widget: "markdown"
        i18n: true




#  - name: "settings"
#    label: "Settings"
#    identifier_field: label
#    i18n:
#      structure: single_file
#      locales: [el, en]
#    files:
#      - name: "translations"
#        label: "Translations"
#        file: _data/translations2.yml
#        i18n: true
#        fields:
#          - name: data
#            label: Data
#            widget: list
#            fields:
#              - {label: Name, name: name, widget: string, i18n: true}
#              - {label: Value, name: value, widget: string, i18n: true}
#
