backend:
  name: git-gateway
  branch: master

publish_mode: 'editorial_workflow'
media_folder: 'assets/files'  # Media files will be stored in the repo under assets/files

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Products"
        name: "products"
        file: "_data/test.yml"
        fields:
          - label: Products
            name: products
            widget: list
            fields:
              - {label: English, name: en, widget: string}
              - {label: Greek, name: el, widget: string}
              - {label: Description English, name: description_en, widget: string}
              - {label: Description Greek, name: description_el, widget: string}
              - {label: Image, name: image_main, widget: image}
              - {label: Image Thumb, name: image_thumb, widget: image}
              - {label: Categories, name: categories, widget: string}
