backend:
  name: git-gateway
  branch: master

publish_mode: 'editorial_workflow'
media_folder: 'assets/img'  # Media files will be stored in the repo under assets/files

collections:
  - name: products
    label: Products
    folder: _products
    sort: name
    create: true
    slug: "{{name}}"
    fields:
      - {label: "Name EN", name: "name_en", widget: "string"}
      - {label: "Name GR", name: "name_el", widget: "string"}
      - {label: "Description EN", name: "description_en", widget: "string"}
      - {label: "Description GR", name: "description_el", widget: "string"}
      - {label: "Image Main", name: "image_main", widget: "image", required: false }
      - {label: "Image 150", name: "image_150", widget: "image", required: false }
      - {label: "Image 300", name: "image_300", widget: "image", required: false }
      - {label: "Categories", name: "categories", widget: "list"}
#  - name: setup
#    label: Setup
#    files:
#      - file: _data/settings.yml
#        label: All Items
#        name: settings_items
#        fields:
#          - label: Settings
#            name: settings_list
#            widget: list
#            fields:
#              - {label: Label, name: label, widget: string}
#              - {label: Value, name: value, widget: string}
